apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-agent
  name: onprem-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-agent
  namespace: onprem-system
  labels:
    control-plane: controller-agent
spec:
  selector:
    matchLabels:
      control-plane: controller-agent
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-agent
    spec:
      containers:
      - command:
        - /agent
        image: quay.io/ifont/onprem-agent:latest
        name: agent
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - name: hub-cluster-secret
          mountPath: /etc/hub-cluster-secret
          readOnly: true
        - name: hub-cluster-configmap
          mountPath: etc/hub-cluster-configmap
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: hub-cluster-secret
        secret:
          secretName: hub-cluster
      - name: hub-cluster-configmap
        configMap:
          name: hub-cluster
